version: "3.5"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        #volumes:
            #- ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            #- ./www:/var/www/html
            #- ./logs:/var/log/ngin
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.docker.network=traefik-net
        - traefik.frontend.rule=Host:api.docker-example.local
        - traefik.port=3000
    networks:
      - traefik-net
      - start-net
